### ISSUE TITLE
Some streams won't load

### ISSUE THREAD

**Issue by d50014** [mkoterle/twitchls#9] opened 2016-07-13 13:38 UTC
I can't load Puhdado's channel, video stays paused and won't play. But I can load like CohhCarnage's stream correctly, I have Chromium 54.

**Comment by mkoterle** [comment] 2016-07-13 20:30
Sadly I can't reproduce this. Do you have issues with some other streams? Try doing the usual - clearing the cache, cookies etc. If you load this exact stream on twitch.tv does it work?

And lastly try opening it in Incognito mode.

**Comment by d50014** [comment] 2016-07-13 21:11
Puhdado's stream does load correctly in Incognito Mode but not in default Tab Mode. Not entirely sure what is causing this issue. Tried to clear cookies and cache, Puhdado's stream does also open correctly on Twitch.tv but not in Twitchls which is weird. I need to check more streamers in Twitchls to report back to you.

**Comment by d50014** [comment] 2016-07-18 18:37
If I disable uBlock Origin extension then I can load Puhdado's stream in normal Tab mode in Twitchls, what makes this weird though is that when I load Puhdado's stream in Incognito Mode in Twitchls I can keep uBlock Origin extension enabled and stream will still load correctly.

**Comment by d50014** [comment] 2016-07-18 18:42
Also another workaround for this is that if you disable Flash Player plug-in then you can load Puhdado's stream in normal Tab mode and with uBlock Origin extension enabled, but this workaround only works time to time. (Not all streams will load correctly though even with this workaround)

**Comment by mkoterle** [comment] 2016-07-20 20:11
The twitch chat is just embedded so I can't control it's dependencies. It loads a bunch of other scripts and some are blocked by ad blockers. I don't think I have control over this problem. I will close it since I can't resolve it. 

If you find some sort of workaround that works, please post it here so we can help others with similar problems.

**Closed by mkoterle** 2016-07-20 20:11 UTC
